### ISSUE TITLE
Add playing instruction on the README.md

### ISSUE THREAD

**Issue by tom-peter12** [SrVariable/RubikCube#9]
There should be more instructions on how to play the game on your README.md file. It's kind of hard to figure out what's the expected input from the user inorder to perform certain tasks. It would be wise to list all the instruction and their supposed behaviors.

**Comment by SrVariable** [comment]
Thank you for the suggestion!
I've just implemented it, you can check it here 943637638c22b09bea1d472f50e714f656472169!
What else do you think I could add?
